name: Checkout submodules
description: Checkout submodules

runs:
  using: "composite"
  steps:
    - name: Install ZAP
      shell: bash
      run: |
        wget https://github.com/project-chip/zap/releases/download/v2024.08.27/zap-linux-x64.zip
        unzip zap-linux-x64.zip -d /opt/silabs/zap-linux-x64
        rm zap-linux-x64.zip

