name: Checkout submodules
description: Checkout submodules

runs:
  using: "composite"
  steps:
    - name: Install java
      shell: bash
      run: |
        wget https://corretto.aws/downloads/resources/17.0.8.8.1/amazon-corretto-17.0.8.8.1-linux-x64.tar.gz
        tar -xzf amazon-corretto-17.0.8.8.1-linux-x64.tar.gz -C $(pwd)
        rm amazon-corretto-17.0.8.8.1-linux-x64.tar.gz
    - name: install SLC CLI
      shell: bash
      run: |
        wget https://www.silabs.com/documents/login/software/slc_cli_linux.zip 
        unzip slc_cli_linux.zip -d $(pwd)
        rm slc_cli_linux.zip
    - name: Install ZAP
      shell: bash
      run: |
        wget https://github.com/project-chip/zap/releases/download/v2024.08.27/zap-linux-x64.zip
        unzip zap-linux-x64.zip -d $(pwd)
        rm zap-linux-x64.zip
    - name: Install Simplicity Commander
      shell: bash
      run: |
        wget https://www.silabs.com/documents/public/software/SimplicityCommander-Linux.zip
        unzip SimplicityCommander-Linux.zip -d $(pwd)/simplicity-commander
        rm SimplicityCommander-Linux.zip
        FILE=$(find $(pwd)/simplicity-commander -name "*Commander_linux_x86_64*")
        if [ -n "$FILE" ]; then
          echo "$FILE"
          tar -xjvf "$FILE" -C $(pwd)/simplicity-commander
        else
          echo "File not found"
        fi
    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      id: arm-none-eabi-gcc-action
      with:
        release: '12.2.Rel1'

    - name: Set ARM_GCC_DIR and POST_BUILD_EXE
      shell: bash
      run: |
        echo "JAVA17_HOME=$(pwd)/amazon-corretto-17.0.8.8.1-linux-x64" >> $GITHUB_ENV
        echo "${{ JAVA17_HOME}}/bin" >> $GITHUB_PATH
        echo "${{ SLC_PATH}}" >> $GITHUB_PATH
        echo "SLC_PATH=$(pwd)/slc_cli/slc " >> $GITHUB_ENV
        echo "ARM_GCC_DIR=${{ steps.arm-none-eabi-gcc-action.outputs.path }}/.." >> $GITHUB_ENV
        echo "POST_BUILD_EXE=$(pwd)/simplicity-commander/commander/commander" >> $GITHUB_ENV

