name: Checkout submodules
description: Checkout submodules

runs:
  using: "composite"
  steps:
    - name: Install ZAP
      shell: bash
      run: |
        wget https://github.com/project-chip/zap/releases/download/v2024.08.27/zap-linux-x64.zip
        unzip zap-linux-x64.zip -d $(pwd)/zap-linux-x64
        rm zap-linux-x64.zip
    - name: Install Simplicity Commander
      shell: bash
      run: |
        wget https://www.silabs.com/documents/public/software/SimplicityCommander-Linux.zip
        unzip SimplicityCommander-Linux.zip -d $(pwd)/simplicity-commander
        rm SimplicityCommander-Linux.zip
        FILE=$(find $(pwd)/simplicity-commander -name "*Commander_linux_x86_64*")
        if [ -n "$FILE" ]; then
          echo "$FILE"
          tar -xjvf "$FILE" -C $(pwd)/simplicity-commander
        else
          echo "File not found"
        fi
    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      id: arm-none-eabi-gcc-action
      with:
        release: '12.2.Rel1'

    - name: install SLC CLI
      run: |
        wget wget https://www.silabs.com/documents/login/software/slc_cli_linux.zip 
        tar unzip ./slc_cli_linux.zip -d $(pwd)/slc_cli_linux 
        rm slc_cli_linux.zip
        echo "SLC_PATH=$(pwd)/slc_cli_linux " >> $GITHUB_ENV

    - name: Set ARM_GCC_DIR and POST_BUILD_EXE
      shell: bash
      run: |
        echo "PATH="${PATH}:/opt/silabs/slc_cli/" >> $GITHUB_ENV"
        echo "ARM_GCC_DIR=${{ steps.arm-none-eabi-gcc-action.outputs.path }}/.." >> $GITHUB_ENV
        echo "POST_BUILD_EXE=$(pwd)/simplicity-commander" >> $GITHUB_ENV

