name: Build Examples

on:
    push:
    pull_request:

jobs:
  thread_build:
    runs-on: ubuntu-latest
    name: EFR32 Thread
    strategy:
      matrix:
        board: [brd4187c, brd4316a, brd4337a]
        app: [dishwasher-app, light-switch-app, lighting-app, lock-app, onoff-plug-app, sensor-app, thermostat, window-app]
        ncp: [thread]

    
    container:
      image: ghcr.io/siliconlabssoftware/simplicity-sdk:latest
      volumes:
        - "/tmp/bloat_reports:/tmp/bloat_reports"
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          # TODO: don't check out simplicity sdk and wifi sdk as a submodule

#      - name: Jfrog CLI setup
#        uses: jfrog/setup-jfrog-cli@v4
#        with:
#          version: latest

      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        id: arm-none-eabi-gcc-action
        with:
          release: '12.2.Rel1'

      - name: Install ZAP
        run: |
          wget https://github.com/project-chip/zap/releases/download/v2024.08.27/zap-linux-x64.zip
          unzip zap-linux-x64.zip -d /opt/silabs/zap-linux-x64
          rm zap-linux-x64.zip

      - run: pwd
      - run: ls

      - name: Move extension to its proper location
        run: |
          mkdir -p ${SISDK_ROOT}/extension/
          cd ..
          cp -r matter_extension ${SISDK_ROOT}/extension
# TODO unnecessary copy of matter_extension to simplicity_sdk

      - name: SLC Generate
        run: |
          export STUDIO_ADAPTER_PACK_PATH=/opt/silabs/zap-linux-x64
          slc configuration --sdk ${SISDK_ROOT}
          slc signature trust  --extension-path "${SISDK_ROOT}/extension/matter_extension/"
          slc signature trust --sdk ${SISDK_ROOT}
          slc generate --daemon -d ${SISDK_ROOT}/extension/matter_extension/${{ matrix.board }}/${{ matrix.app }}-${{ matrix.ncp }} -p ${SISDK_ROOT}extension/matter_extension/slc/sample-app/${{ matrix.app }}/efr32/${{ matrix.app }}-${{ matrix.ncp }}.slcp --with ${{ matrix.board }} --generator-timeout=180

      - name: SLC Build
        run: |
          export ARM_GCC_DIR=${{ steps.arm-none-eabi-gcc-action.outputs.path }}/..
          make all -C ${SISDK_ROOT}/extension/matter_extension/${{ matrix.board }}/${{ matrix.app }}-${{ matrix.ncp }} -f ${{ matrix.app }}-${{ matrix.ncp }}.Makefile -j8

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}-${{ matrix.ncp }}
          path: ${SISDK_ROOT}/extension/matter_extension/${{ matrix.board }}/${{ matrix.app }}-${{ matrix.ncp }}
          

