name: Build Examples

on:
    push:
    pull_request:

jobs:
  thread_build:
    name: EFR32 Thread

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/siliconlabssoftware/matter_extension_dependencies:test_arm_commander
      volumes:
        - "/tmp/bloat_reports:/tmp/bloat_reports"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install ZAP
        run: |
          wget https://github.com/project-chip/zap/releases/download/v2024.08.15/zap-linux-x64.zip
          unzip zap-linux-x64.zip -d /opt/silabs/zap-linux-x64
          rm zap-linux-x64.zip

      - name: Move extension to its proper location
        run: |
          mkdir -p ${SISDK_ROOT}/extension/matter_extension
          rsync -av ./* ${SISDK_ROOT}/extension/matter_extension --exclude sisdk --exclude ci --exclude jenkins --exclude Jenkinsfile --exclude third_party/matter_sdk/third_party  --exclude third_party/simplicity_sdk --exclude third_party/wifi_sdk --exclude third_party/wiseconnect-wifi-bt-sdk > /dev/null 2>&1

      - name: SLC Generate
        run: |
          export STUDIO_ADAPTER_PACK_PATH=/opt/silabs/zap-linux-x64
          slc configuration --sdk /opt/silabs/simplicity_sdk
          slc signature trust  --extension-path "/opt/silabs/simplicity_sdk/extension/matter_extension/"
          slc signature trust --sdk /opt/silabs/simplicity_sdk
          slc generate --daemon -d /opt/silabs/simplicity_sdk/extension/matter_extension/brd4187c/lighting -p /opt/silabs/simplicity_sdk/extension/matter_extension/slc/sample-app/lighting-app/efr32/lighting-app-thread.slcp --with brd4187c --generator-timeout=180

      - name: SLC Build
        run: |
          export POST_BUILD_EXE=/opt/silabs/simplicity-commander/commander/commander
          make all -C /opt/silabs/simplicity_sdk/extension/matter_extension/brd4187c/lighting -f lighting-app-thread.Makefile -j13