name: Build and Generate

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      board:
        required: true
        type: string
      board_extension:
        required: false
        type: string
      suffix:
        required: true
        type: string
      family:
        required: true
        type: string
      addAppComponent:
        required: false
        type: string
      removeAppComponent:
        required: false
        type: string
      optionalSlcParams:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run setup script
        shell: bash
        run: |
          ls -la  ${{ github.workspace }}

      - name: Default additional component string
        run: echo "ADD_APP_COMPONENT_STRING=--with ${{ inputs.board }}${{ inputs.board_extension }}" >> $GITHUB_ENV

      - name: Create string out of additional components
        if: ${{ inputs.addAppComponent != '' }}
        run: 
          echo "ADD_APP_COMPONENT_STRING=${ADD_APP_COMPONENT_STRING},${{ inputs.addAppComponent }}" >> $GITHUB_ENV

      - name: Create string out of removed components
        if: ${{ inputs.removeAppComponent != '' }}
        run: echo "REMOVE_APP_COMPONENT_STRING=--without ${{ inputs.removeAppComponent }}" >> $GITHUB_ENV

      - name: SLC Generate
        run: |
         slc  --java-location=${"JAVA17_HOME}  generate --daemon -d ${MATTER_EXTN_ROOT}/${{ inputs.board }}/${{ inputs.app }}-${{ inputs.suffix }} -p $MATTER_EXTN_ROOT/$(SLC_PATH)/${SLC_PATH}/sample-app/${{ inputs.app }}/${{ inputs.family }}/${{ inputs.app }}-${{ inputs.suffix }}.slcp ${ADD_APP_COMPONENT_STRING} ${REMOVE_APP_COMPONENT_STRING} --generator-timeout=180

      - name: Build
        run: |
          export ARM_GCC_DIR=${{ env.ARM_GCC_DIR }}
          export POST_BUILD_EXE=${{ env.POST_BUILD_EXE }}
          make all -C ${MATTER_EXTN_ROOT}/${{ inputs.board }}/${{ inputs.app }}-${{ inputs.suffix }} -f ${{ inputs.app }}-${{ inputs.suffix }}.Makefile -j8

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app }}-${{ inputs.suffix }} ${{ inputs.board }}
          path: ${MATTER_EXTN_ROOT}/${{ inputs.board }}/${{ inputs.app }}-${{ inputs.suffix }}/build/debug/${{ inputs.app }}-${{ inputs.suffix }}.s37
          