name: EFR32 Build

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      board:
        required: true
        type: string
      ncp:
        required: true
        type: string

jobs:
  thread_build:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/siliconlabssoftware/simplicity-sdk:latest
      volumes:
        - "/tmp/bloat_reports:/tmp/bloat_reports"
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
# TODO don't check out simplicity_sdk, wifi_sdk, wiseconnect-bt-sdk and matter_private

#      - name: Jfrog CLI setup
#        uses: jfrog/setup-jfrog-cli@v4
#        with:
#          version: latest

      - name: Install Simplicity Commander
        run: |
          wget https://www.silabs.com/documents/public/software/SimplicityCommander-Linux.zip
          unzip SimplicityCommander-Linux.zip -d /opt/silabs/simplicity-commander
          rm SimplicityCommander-Linux.zip
          FILE=$(find /opt/silabs/simplicity-commander/ -name "*Commander_linux_x86_64*")
          if [ -n "$FILE" ]; then
            echo "$FILE"
            tar -xjvf "$FILE" -C /opt/silabs/simplicity-commander
          else
            echo "File not found"
          fi

      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        id: arm-none-eabi-gcc-action
        with:
          release: '12.2.Rel1'

      - name: Install ZAP
        run: |
          wget https://github.com/project-chip/zap/releases/download/v2024.08.27/zap-linux-x64.zip
          unzip zap-linux-x64.zip -d /opt/silabs/zap-linux-x64
          rm zap-linux-x64.zip
 
      - name: Set up Simplicity SDK environment variable 
        run: |
          echo "simplicitySdkPath=${SISDK_ROOT}" >> $GITHUB_ENV

      - name: Copy matter_extension to simplicity_sdk and set Matter Extension Environment Variable
        run: |
          mkdir -p ${{ env.simplicitySdkPath }}/extension
          cd ..
          cp -r matter_extension ${{ env.simplicitySdkPath }}/extension
          echo "matterExtensionPath=${{ env.simplicitySdkPath }}extension/matter_extension" >> $GITHUB_ENV
          echo "STUDIO_ADAPTER_PACK_PATH=/opt/silabs/zap-linux-x64" >> $GITHUB_ENV

      - name: Copy wifi_sdk to simplicity_sdk and set Wi-Fi SDK Environment Variable
        run: |
          mv /opt/silabs/wifi_sdk ${{ env.simplicitySdkPath }}/extension
          echo "wifiSdkPath=${{ env.simplicitySdkPath }}extension/wifi_sdk" >> $GITHUB_ENV
          mv /opt/silabs/wiseconnect-wifi-bt-sdk ${{ env.simplicitySdkPath }}/extension
          echo "wiseconnectSdkPath=${{ env.simplicitySdkPath }}extension/wiseconnect-wifi-bt-sdk" >> $GITHUB_ENV

      - name: SLC Generate
        run: |
          slc configuration --sdk ${{ env.simplicitySdkPath }}
          slc signature trust --extension-path "${{ env.matterExtensionPath }}"
          slc signature trust --extension-path "${{ env.wifiSdkPath }}"
          slc signature trust --sdk ${{ env.simplicitySdkPath }}
          slc generate --daemon -d ${{ env.matterExtensionPath }}/${{ inputs.board }}/${{ inputs.app }}-${{ inputs.ncp }} -p ${{ env.matterExtensionPath }}/slc/sample-app/${{ inputs.app }}/efr32/${{ inputs.app }}-${{ inputs.ncp }}.slcp --with ${{ inputs.board }} --generator-timeout=180

      - name: Build
        run: |
          export POST_BUILD_EXE=/opt/silabs/simplicity-commander/commander/commander
          export ARM_GCC_DIR=${{ steps.arm-none-eabi-gcc-action.outputs.path }}/..
          make all -C ${{ env.matterExtensionPath }}/${{ inputs.board }}/${{ inputs.app }}-${{ inputs.ncp }} -f ${{ inputs.app }}-${{ inputs.ncp }}.Makefile -j8

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app }}-${{ inputs.ncp }} ${{ inputs.board }}
          path: ${{ env.matterExtensionPath }}/${{ inputs.board }}/${{ inputs.app }}-${{ inputs.ncp }}/build/debug/${{ inputs.app }}-${{ inputs.ncp }}.s37
          

